language: php
sudo: required
dist: precise

matrix:
  include:
    - php: 5.3.3
      env: DB=mysqli
    - php: 5.3
      env: DB=mysqli # MyISAM
    - php: 5.4
      env: DB=mysqli
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=mariadb
    - php: 5.4
      env: DB=postgres
    - php: 5.4
      env: DB=sqlite3
    - php: 5.4
      env: DB=mysqli;SLOWTESTS=1
    - php: 5.5
      env: DB=mysqli
    - php: 5.6
      env: DB=mysqli
    - php: hhvm
      env: DB=mysqli
  allow_failures:
    - php: hhvm
  fast_finish: true

env:
  global:
    - EXTNAME="board3/portal"
    - SNIFF="1"        # Should we run code sniffer on your code?
    - IMAGE_ICC="0"    # Should we run icc profile sniffer on your images?
    - COVERAGE="1"     # Should we send coverage?
    - EPV="1"          # Should we run EPV (Extension Pre Validator) on your code?
    - SPELLCHECK="1"   # Should the php files be checked for obvious spelling errors?
    - PHPBB_BRANCH="3.1.x"

branches:
  except:
    - 2.0.x
    - develop-1_0_X

install:
  - php composer.phar install --dev --no-interaction --prefer-source
  - travis/prepare-phpbb.sh $EXTNAME $PHPBB_BRANCH
  - cd ../../phpBB3
  - travis/prepare-extension.sh $EXTNAME $PHPBB_BRANCH
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION
  - sh -c "if [ '$COVERAGE' != '0' ]; then ../board3/Board3-Portal/travis/prepare-coverage.sh $DB $TRAVIS_PHP_VERSION; fi"

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION
  - mkdir build/logs
  - chmod +wx build/logs

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTNAME; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - ../board3/Board3-Portal/travis/run-testsuite.sh $DB $TRAVIS_PHP_VERSION
  - sh -c "if [ '$EPV' != '0' ]; then ../board3/Board3-Portal/travis/run-epv.sh $DB $TRAVIS_PHP_VERSION $EXTNAME; fi"

after_script:
  - sh -c "if [ '$COVERAGE' != '0' ]; then ../board3/Board3-Portal/travis/send-coverage.sh $DB $TRAVIS_PHP_VERSION; fi"

notifications:
  email:
    recipients:
      - admin@m-a-styles.de
    on_success: change
    on_failure: change
